apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - https://raw.githubusercontent.com/katexochen/sync/9567164967b5832fb4992088af89dbbd94184043/server/deployment.yml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector
        value: {"ci.contrast.edgeless.systems/main-runner": "true"}
    target:
      kind: StatefulSet
