#
# This config checks external links.
# It doesn't check the fragments of external links, as it isn't able to relyably detect them
# from sites like GitHub.
#

no_progress = true
cache = false
include_fragments = false
retry_wait_time = 20
fallback_extensions = ["md", "html"]
exclude = [
    '^https://mysql\.com/', # returns 403
    '^http(s)?://localhost',
    '^https://github\.com/edgelesssys/contrast/(settings|deployments)', # not public
    '^https://.*\.hashicorp\.com', # strict bot protection
    '^https://.*\.medium\.com', # strict bot protection
]
exclude_path = [
    "dev-docs/frozen",
]
exclude_link_local = true

# lychee in-run caching is bugged
# https://github.com/lycheeverse/lychee/issues/1593
threads = 1
max_concurrency = 1
