#
# This config only checks the internal links between docs pages.
# It also checks for the correctness of local fragments.
#

no_progress = true
cache = false
include_fragments = true
fallback_extensions = ["md", "html"]

# We're only using absolute paths for assets from this directory (which are copied into the
# rendered tree, see https://docusaurus.io/docs/static-assets).
root_dir = 'docs/static'

exclude = [ '^http' ]
exclude_path = [ "dev-docs/frozen" ]

# lychee in-run caching is bugged
# https://github.com/lycheeverse/lychee/issues/1593
threads = 1
max_concurrency = 1
