apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: csi-system

resources:
  - namespace.yaml
  # keep-sorted start
  - csi-attacher-rbac.yaml
  - csi-health-rbac.yaml
  - csi-hostpath-driverinfo.yaml
  - csi-hostpath-plugin.yaml
  - csi-provisioner-rbac.yaml
  - csi-resizer-rbac.yaml
  - csi-snapshotter-rbac.yaml
  - csi-storageclass.yaml
  # keep-sorted end

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: hostpath.csi.k8s.io
      app.kubernetes.io/part-of: csi-driver-host-path
